# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.iti.sips
canonical: https://profiles.ihe.net/ITI/sIPS
version: 0.0.1-current
name: IHE_ITI_sIPS
title: "Sharing of IPS"
description: Sharing of IPS (sIPS) - defines how HL7 FHIR IPS is communicated using IHE Document Sharing
releaseLabel: ci-build
#releaseLabel: Trial-Implementation
#date: 2022-01-02
status: draft
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  name: IHE IT Infrastructure Technical Committee
  url: https://www.ihe.net/ihe_domains/it_infrastructure/
  email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2023+
#extension: 
#  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
#    valueCode: draft
#  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
#    valueInteger: 0
    
dependencies:
  hl7.fhir.uv.ips:
    id: hl7ips
    uri: http://hl7.org/fhir/uv/ips/ImplementationGuide/hl7.fhir.uv.ips
    version: 1.0.x
  ihe.iti.mhd: 
  # Depend on MHD so that the DocumentReference examples have proper profiling
    id: iheitimhd
    uri: https://profiles.ihe.net/ITI/MHD/ImplementationGuide/ihe.iti.mhd
    version: 4.2.x

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

# resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate. The order they appear here is the order they will appear in the TOC and on the next/prev navigation.
  index.md:
    title: 1:56 sIPS Home
    generation: markdown
  volume-1.md:
    title: 1:56 sIPS Volume 1
    generation: markdown
  content.md:
    title: 3:5.9 IPS Content Module
    generation: markdown
  testplan.md:
    title: Test Plan
    generation: markdown
  other.md:
    title: Changes to Other Documents
    generation: markdown
  download.md:
    title: Download and Analysis
    generation: markdown
  issues.md:
    title: Significant Changes & Issues
    generation: markdown
  pcc.md:
    title: PCC Volume 2 excerpt
    generation: markdown

menu:
  Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#actors-and-transactions
    Actor Options: volume-1.html#actor-options
    Required Groupings: volume-1.html#required-groupings
    Overview: volume-1.html#overview
    Security Considerations: volume-1.html#security-considerations
    Cross-Profile Considerations: volume-1.html#other-grouping
  Volume 3: content.html
  Artifacts: artifacts.html
  Other:
    Test Plan: testplan.html
    Changes to Other IHE Specifications: other.html
    Download and Analysis: download.html
  PCC Excerpt: pcc.html